#index:
#    path: /
#    controller: App\Controller\DefaultController::index

article_show:
  path: /article/{id}
  controller: App\Controller\ArticleController::show
# new_article:
#   path: /article/new
#   controller: App\Controller\ArticleController::show
